### ISSUE TITLE
App description should state root requirement

### ISSUE THREAD

**Issue by vertigo220** [MuntashirAkon/BatteryChargeLimiter#18]
While I wasn't surprised when I installed this only to find it won't work without root, I was hoping something had changed to allow this functionality without it since nowhere in the app description in the store or even in the screenshots was anything mentioned about root being required. This should be in prominent text at the beginning of the app description.

**Comment by Korb** [comment]
Currently on F-Droid the following description of the application:

> Control when to start and stop charging your battery
> Battery Charge Limiter (BCL) is a fork of Battery Charge Limit whose development has been stalled for some time.
> This app is a work in progress. If a feature is not working, do not hesitate to file a report.
> 
> Features:
> 
> - Free and open source.
> - Material 3 with dynamic colours.
> - Control when to start and stop charging - either directly or via an widget.
> - Set voltage threshold.
> - Set custom battery control configuration if the supplied ones cannot be used properly.
> 
> Same as ACC?
> ACC offers a broad range of features which might be too much for some people.
> 
> Troubleshooting
> If BCL cannot start or stop charging correctly, enable Always Write CTRL File in the settings.

That is, I confirm that now there is no mention of the indispensable presence of root in the description.

**Comment by MuntashirAkon** [comment]
> Currently on F-Droid the following description of the application:

I see. OP didn't mention anything about F-Droid which was confusing since the README section clearly mentioned it.

**Comment by jaredcat** [comment]
Is it possible to leverage Shizuku for non-rooted phones?

**Comment by MuntashirAkon** [comment]
> Is it possible to leverage Shizuku for non-rooted phones?

No, activating or deactivating charging exclusively requires root.

**Comment by MuntashirAkon** [comment]
F-Droid description updated via 932fedb2b41b6b112d32e73f552e8f8a72580595
