### ISSUE TITLE
App crashes while opening 

### ISSUE THREAD

**Issue by Felix-Kyun** [MuntashirAkon/BatteryChargeLimiter#19]
Welp i installed the app and tried to open it and it opened but it crashed as soon as I clicked enable it crahsed and now it doesn't even open 
Logs : [bcl.log](https://github.com/MuntashirAkon/BatteryChargeLimiter/files/10354573/bcl.log)

**Comment by nfriedly** [comment]
Same here - I'm using a moto g100 running LineageOS 20 (Android 13), rooted with magisk. The older Battery Charge Limit app that this is based off of does work, so I switched to that one for now.

I installed through f-droid, if that makes a difference.

**Comment by MuntashirAkon** [comment]
Duplicate of #24
